#Ce fichier concerne les configurations de la réception MQTT. 
#Les données qui existent ici doivent être gérés par un programme externe. 
#Par exemple, le topic MQTT qui existent sur ce fichier doivent être déduites par un programme selon l'identifiant du routeur.

broker:
   host: "test.mosquitto.org" #Le host doit être modifié par le bon host, en pratique c'est local host (dans le raspberry)
   port: 1883 #Le port doit être modifié par le bon port, en pratique c'est 1883
   username:  ""     #Facultatif, ça sert surtout en cas de broker public & si l'utilisateur se soucie de la sécurité
   password:  ""     #Facultatif, ça sert surtout en cas de broker public & si l'utilisateur se soucie de la sécurité

client_id: "Optimasol" # ça sert pour que l'utilisateur voit dans une interface routeur ce que le logiciel récupère.

topic : "PV111/DATA" # C'est le topic qui concerne les données envoyées par le routeur. 