#Le but de ce fichier c'est de définir les paramètres liées aux panneaux solaires.
#Le programme d'interface doit interagir avec ces fichiers pour ajuster les paramètres. 
#Ces configurations concernent en réalité tout le système solaire (panneaux + Onduleur + câbles)


Onduleur :
   efficacite : 0.96
   plafond_puissance : 1000 # en W, plafond de puissance de l'onduleur.
   pertes_cables : 0.01 # entre 0 et 1, pertes dans les câbles.

rendement_global : 0.2 #C'est le rendement qu'on utilise en cas de problème avec PVLIB ou si l'utilisateur ne connait pas les caractéristiques.

panneaux :
#-------------PANNEAU 1-----------------------------------------------------
    -   azimuth : 180 # en degrés, 0 = Nord, 90 = Est, 180 = Sud, 270 = Ouest
        tilt : 30 # en degrés, 0 = horizontal, 90 = vertical
        puissance_nominale : 400 # en Wc (W crête) 
        #------------------------------------
        #Si on passe pas par Pvlib : 
        surface_panneau : 2 # en m2
#--------------PANNEAU 2-----------------------------------------------------
    -   azimuth : 90 # en degrés, 0 = Nord, 90 = Est, 180 = Sud, 270 = Ouest
        tilt : 30 # en degrés, 0 = horizontal, 90 = vertical
        puissance_nominale : 400 # en Wc (W crête) 
        #------------------------------------
    
        #Si on passe pas par Pvlib : 
        surface_panneau : 2 # en m2



    # On peur ajouter d'autres panneaux si on veut. 

