#Le but de ce fchier de configuration est de définir des variables de la position géographique de l'installation.
#On rappelle que le programme d'interface doit interagir avec ces fichiers de configs pour ajuster les paramètres.



latitude : 50.6666 # en degrés décimaux (il faut veiller à ce qu'il y a suffisamment de décimales pour la précision) 
longitude : 3.0833 # en degrés décimaux (il faut veiller à ce qu'il y a suffisamment de décimales pour la précision)
altitude : 35 # en mètres 
ville : "Lille" # nom de la ville pour affichage (pas forcémet utile mais parfois des Apis le demandent) 
fuseau_horaire : "Europe/Paris" # fuseau horaire (nécessaire dans les APIs et dans PVLib)
