#Ce fichier de configurations concerne les paramètres généraux et les préférences du client. 

requetes :
   frequence_rafraichissement : 300 # en minutes, fréquence de mise à jour des données météo
   pas_de_temps : 15 # en minutes, pas de temps entre deux prévisions
   horizon_temporel : 48 # en heures, durée totale de l'horizon des prévisions.


features :
   selection_fournisseur : 0 #Ou bien le nom direct du fournisseur (string) 0 correspond au mode par défaut.
   ajusteur_ranking : false #True ou False, si True, on ajuste le ranking des fournisseurs en fonction de la précision observée.
   ajusteur_parametres : false #True si l'utilisateur veut qu'on corrige les paramètres des panneaux en fonction de ce qu'on calcule / mesure.
   IA_model : false #True si on utilise la fonctionalité ML pour amléiorer la précision
   fournisseur_propre : 0 #0 si pas de fournisseur propre, 1 si oui et automatique, 2 si oui mais manuel (si 1 voir les configs fournisseur_propre.yaml)




